require("zemzale.plugins")
require("zemzale.custom")
require("zemzale.telescope")
require("zemzale.lsp")
require("zemzale.keymaps")
require("zemzale.colors")
require("zemzale.auto")
require("zemzale.treesitter")
